### ISSUE TITLE
Cannot attach cy.screenshot()

### ISSUE THREAD

**Issue by Phenomite** [webnexusmobile/cypress-cucumber-getting-started#1]
Hi, great work!

Just a quick thing, addScreenshots() uses regex that will fail on cy.screenshot() due to naming convention cypress uses, would it be possible to add this feature in the future?

Regards.

**Comment by zettpunkt79** [comment]
Hi,

I just added the capability to add regular screenshots to the report. Since cy.screenshot() will usually occur in steps which do not fail we need some sort of indicator to which passing step we would like the screenshot to be attached. I decided to attach it to the first step in a scenario which has "screenshot" in the step name.

Hope that helps :)

**Comment by Phenomite** [comment]
Yea that feels too much of a compromise, I'll try looking at the preprocessor to see if I can fork it to insert the screenshot to the json generation.

**Comment by jcundill** [comment]
Hi @webnexusmobile  

I have recently picked up the add cy.log and cy.screenshot output to the json report task again. WIP is https://github.com/jcundill/cypress-cucumber-preprocessor/tree/logandscreenshot

Still a bit to do - e.g. ensure that `After`s always get called so we don't drop those logs etc- and some tidy up, but hopefully I can get a PR out soonish. In conjunction with the done work here that should give pretty good coverage

**Comment by begli80** [comment]
Hi @webnexusmobile
I urgently need help with screenshot attachment.Cannot attach the screenshots for failed tests if the path is :
const screenshotsDir = './cypress/screenshots'
Because cypress generates subfolders under the screenshots folder with spec file names and .png is preserved in those folders.But if I provide the full path to the .png file then it attaches. But that path works for only one specific .png file.Because when the tests fail, there are multiple folders with spec names created.Has it got anything to do with 'const regex = /(?<=--\ ).+?((?=\ \(example\ #\d+\))|(?=\ \(failed\))|(?=\.\w{3}))/g'.   that you put in the report.js ? 
I'm not good with regex so do not understand what that regex means.Help is appreciated

**Comment by zettpunkt79** [comment]
Hi @begli80
If './cypress/screenshots' is your configured screenshots directory, you should be fine, because the reporter iterates over any failed feature directories within this folder. The regex is there to get the failing step name from the screenshot's filename so we can look for that failing step name in the feature's *.cucumber.json report and attach the screenshot there.

The regex you are citing is not identical to the regex in the custom-html-reporter.js. Please check on that. The purpose of the regex is described in the comments above the regex and you can verify if the regex works for the naming scheme of your screenshot file names here:

https://regex101.com/r/edHGVr/2

**Comment by begli80** [comment]
Hi @webnexusmobile
Thank you for the reply.Actually my screenshots folder is './cypress/screenshots' and that's why my attachments fail unless I provide full path to the .png file. As I mentioned cypress generates subfolders under the screenshots folder depending on the hierarchy of the failing feature file and under that feature folder it generates the .png file.My assumption is if the regex has got nothing to do with the target folder location then it should be the path to the screenshots responsible for failure to attach. In my project the path to the .png file is :
cypress/screenshots/examples/CS/MSaccount/AddresBookFunctionality.feature/Address Book Functionality -- Verify the user is able to add new address in the address page without  checking Preferred address (failed).png
As you can see there are 4 folders after the screenshots folder to reach the png file, so might that be an issue ?
<img width="846" alt="Screen Shot 2020-04-03 at 3 36 47 PM" src="https://user-images.githubusercontent.com/39811047/78404916-08828500-75c5-11ea-8855-07971e7ae37c.png">

**Comment by Phenomite** [comment]
> Hi @webnexusmobile
> Thank you for the reply.Actually my screenshots folder is './cypress/screenshots' and that's why my attachments fail unless I provide full path to the .png file. 

Hey, I also have this problem, think I'll be addressing it on monday and will tell you how it goes unless the author here solves it beforehand. Basically the regex doesnt account for deeper pathing which can be resolved pretty easily.

**Comment by zettpunkt79** [comment]
The report.js currently only looks into folders which are a direct subfolder of the screenshots folder. This will work fine, if you place all your *.feature files directly into the ./cypress/integration folder. If you choose to put your feature-files into sub-folders or even sub-sub-folders you will have to adjust the report.js so it will crawl to all of your subdirectories within the screenshots-folder to find all of your screenshots. I'm currently fine with placing all of my feature files right into the integration folder so I didn't put any time/effort into crawling for potential other directories.

**Comment by begli80** [comment]
> > Hi @webnexusmobile
> > Thank you for the reply.Actually my screenshots folder is './cypress/screenshots' and that's why my attachments fail unless I provide full path to the .png file.
> 
> Hey, I also have this problem, think I'll be addressing it on monday and will tell you how it goes unless the author here solves it beforehand. Basically the regex doesnt account for deeper pathing which can be resolved pretty easily.

Looking forward to hearing some good news

**Comment by Phenomite** [comment]
> Looking forward to hearing some good news

All done.
Keep in mind this will probably fall over if the folders arent properly populated or passed in (screenshotDir path).

https://gist.github.com/Phenomite/038c57cdaf95b8b8383a0fd522919662

**Comment by begli80** [comment]
Hi Phenomite,
First of all thank you for your effort. Per my understanding do we need to replace the ' function addScreenshots()'  from the webnexusmobile's report.js with the one you provided? 
If so I replaced it and ran and this is what I got :

<img width="774" alt="Screen Shot 2020-04-06 at 9 41 12 AM" src="https://user-images.githubusercontent.com/39811047/78571783-3f86af80-77ec-11ea-829b-30364ad181e5.png">

And what do you mean by "if the folders aren't properly populated or passed" ?

**Comment by Phenomite** [comment]
I mean that my solution is for nonGlobalStepDefinitions: true.

The cucumberReportMap will be populated with something like this:
"bla.feature": [{stuff}],
"2nd test.feature": [{stuff}],

Therefore your error is because the screenshot folder iterator picked up a folder that wasnt named the same as your feature.
E.g. for the example above I would ONLY have these folders (note the png's containing folder):
`cypress\screenshots\junk\bla.feature\test scenario -- 1.png`
`cypress\screenshots\morejunk\2nd test.feature\2nd test scenario -- 2.png`

You must run some form of pretest to `rimraf` and `mkdirp` the screenshots folder, AND the report json folder.

If you still have issues please send a tree view of your cypress folder structure.

**Comment by begli80** [comment]
OK let me show what I have got , here is what in my cucumberReportMap(what I copied from webnexusmobile's report.js) :
function getCucumberReportMaps() {
  const files = fs.readdirSync(cucumberJsonDir).filter(file => {
    return file.indexOf('.json') > -1
  })
  files.forEach(file => {
    const json = JSON.parse(
      fs.readFileSync(path.join(cucumberJsonDir, file))
    )
    if(!json[0]) {return}
    const [feature] = json[0].uri.split('/').reverse()
    **_cucumberReportFileMap[feature] = file
    cucumberReportMap[feature] = json_**
  })
}
As for pretest  rimraf and mkdir I have taken care  of and they run before I run my whole test suite, so there is no issue with deleting and creating new directory.
I have just done another run deleting both cucumber-report folder and screenshots folder to make sure nothing left in those folders but still facing the same issue



And this is my folder structure which is similar to what you mentioned above and you can see the folder has got the same name as the feature file

**Comment by Phenomite** [comment]
Thanks, it was the unix path being "/" rather than "\\" on windows. I have changed this line in the gist:

```
  const featuresList = screenshots.map(x => x.split(/(?:\\|\/)+/).slice(-2)[0])
```

**Comment by begli80** [comment]
Hi Phenomite 
Thank you for your effort and help.It worked.Now able to attach screenshots
<img width="729" alt="Screen Shot 2020-04-06 at 8 48 29 PM" src="https://user-images.githubusercontent.com/39811047/78621483-4cd18780-7848-11ea-891a-ca652c35162c.png">
