### ISSUE TITLE
Problem with attaching screenshots to on demand reports

### ISSUE THREAD

**Issue by jradom** [webnexusmobile/cypress-cucumber-getting-started#7]
Hello,

I was able to successfully attach one error screenshot or on-demand screenshot to a report.  All reports in the same scenario.  I have a problem embed multiple on-demand screenshots for the same scenario.  Only, the first report was embedded and attached to the report.  All other subsequent reports are missing in the final report.
We use parameters in the scenario outline and that is another reason it doesn't link a screenshot to test at all.
PLease, help because we really rely on your report generation from cypress-cucumber-preprocessor
This is one of the features with problem missing second screenshot
@tag_test
Feature: Login Feature
  As a valid customer I'm able to login into CAIR site
  and start creating a case
  Scenario: Login Validation
    Given I am on CAIR login page
    Then I take a screenshot
    When I login as "formalLabDirector" user role
    And I navigate to Assay list page
    Then I take a screenshot
    And I click "Create" button on Assay list page

Project looks like

![image](https://user-images.githubusercontent.com/20550461/105960733-7c998800-6032-11eb-954d-6ae0b5cf7c4b.png)

Thanks a lot in advance

Jeff

**Comment by zettpunkt79** [comment]
Hi, 

I probably have to make clear that this is just a demo project to provide a quick start on how to integrate cypress-cucumber-preprocessor with the multiple-cucumber-html-preprocessor. It was a spare time project were I more or less just integrated the work of other's (see credits in the code) and I am not planning to offer any support. It was never meant to add more than one screenshot to a single scenario. So you if you want to use it as is, you should split up your scenarios. Otherwise you will have to refactor the code so it can handle multiple screenshots in one scenario.

Regards,
Markus
